all: q1 q2 q3 q4 q5 q6 q7 q8

clean:
	rm -f q1 q2 q3 q4

q1: q1.cpp
	g++ -o q1 q1.cpp

q2: q2.cpp
	g++ -o q2 q2.cpp

q3: q3.cpp
	g++ -o q3 q3.cpp

q4: q4.cpp
	g++ -o q4 q4.cpp

q5: q5.cpp
	g++ -o q5 q5.cpp

q6: q6.cpp
	g++ -o q6 q6.cpp

q7: q7.cpp
	g++ -o q7 q7.cpp

q8: q8.cpp
	g++ -o q8 q8.cpp
