all: syscall_test context_switch_test

clean:
	rm syscall_test context_switch_test

syscall_test: syscall_test.cpp
	g++ -o syscall_test syscall_test.cpp

context_switch_test: context_switch_test.cpp
	g++ -o context_switch_test context_switch_test.cpp
